/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felippe
 */
public class TelaPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalAdmin
     */
    public TelaPrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        medico1 = new modelo.Medico();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        consultaAlteraMedico = new javax.swing.JMenuItem();
        cadastrarMedico = new javax.swing.JMenuItem();
        removerMedico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        consultaAlteraSecretaria = new javax.swing.JMenuItem();
        cadastrarSecretaria = new javax.swing.JMenuItem();
        removerSecretaria = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jMenu1.setText("Medico");

        consultaAlteraMedico.setText("Consultar/Alterar");
        consultaAlteraMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaAlteraMedicoActionPerformed(evt);
            }
        });
        jMenu1.add(consultaAlteraMedico);

        cadastrarMedico.setText("Cadastrar");
        jMenu1.add(cadastrarMedico);

        removerMedico.setText("Remover");
        jMenu1.add(removerMedico);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Secretaria");

        consultaAlteraSecretaria.setText("Consultar/Alterar");
        jMenu2.add(consultaAlteraSecretaria);

        cadastrarSecretaria.setText("Cadastrar");
        jMenu2.add(cadastrarSecretaria);

        removerSecretaria.setText("Remover");
        jMenu2.add(removerSecretaria);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaAlteraMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaAlteraMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaAlteraMedicoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
         this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarMedico;
    private javax.swing.JMenuItem cadastrarSecretaria;
    private javax.swing.JMenuItem consultaAlteraMedico;
    private javax.swing.JMenuItem consultaAlteraSecretaria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private modelo.Medico medico1;
    private javax.swing.JMenuItem removerMedico;
    private javax.swing.JMenuItem removerSecretaria;
    // End of variables declaration//GEN-END:variables
}
