/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dadosAdicionais;

/**
 *
 * @author Felippe
 */
public class AlteraDadosAdicionais extends javax.swing.JPanel {

    /**
     * Creates new form AlteraDadosAdicionais
     */
    public AlteraDadosAdicionais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FumaChecBox = new javax.swing.JCheckBox();
        bebeCheckBox = new javax.swing.JCheckBox();
        colesterolCheckBox = new javax.swing.JCheckBox();
        diabeteCheckBox = new javax.swing.JCheckBox();
        doencaCardiacaCheckBox = new javax.swing.JCheckBox();
        cpfText = new javax.swing.JTextField();
        OkButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cirurgiaText = new javax.swing.JTextField();
        doencasCardiacasText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        alterarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Dados Adicionais do Paciente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CPF:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        FumaChecBox.setText("Fuma");

        bebeCheckBox.setText("Bebe");

        colesterolCheckBox.setText("Colesterol");

        diabeteCheckBox.setText("Diabete");

        doencaCardiacaCheckBox.setText("Doença Cardíaca");

        cpfText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        OkButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OkButton.setText("OK");

        jLabel4.setText("jLabel4");

        jLabel5.setText("Cirurgias:");

        jLabel6.setText("Alergias:");

        alterarButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterarButton.setText("Alterar");

        cancelarButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelarButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cirurgiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(doencasCardiacasText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(doencaCardiacaCheckBox)
                            .addComponent(diabeteCheckBox)
                            .addComponent(colesterolCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OkButton))
                            .addComponent(FumaChecBox)
                            .addComponent(bebeCheckBox)
                            .addComponent(jLabel1))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alterarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarButton)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkButton)
                    .addComponent(cpfText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FumaChecBox)
                .addGap(18, 18, 18)
                .addComponent(bebeCheckBox)
                .addGap(18, 18, 18)
                .addComponent(colesterolCheckBox)
                .addGap(18, 18, 18)
                .addComponent(diabeteCheckBox)
                .addGap(18, 18, 18)
                .addComponent(doencaCardiacaCheckBox)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cirurgiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doencasCardiacasText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterarButton)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FumaChecBox;
    private javax.swing.JButton OkButton;
    private javax.swing.JButton alterarButton;
    private javax.swing.JCheckBox bebeCheckBox;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField cirurgiaText;
    private javax.swing.JCheckBox colesterolCheckBox;
    private javax.swing.JTextField cpfText;
    private javax.swing.JCheckBox diabeteCheckBox;
    private javax.swing.JCheckBox doencaCardiacaCheckBox;
    private javax.swing.JTextField doencasCardiacasText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
